#!/bin/bash
psql -U postgres -c 'CREATE DATABASE ekylibre_test;'
psql -U postgres -d ekylibre_test -c 'CREATE SCHEMA IF NOT EXISTS postgis;'
psql -U postgres -d ekylibre_test -c 'CREATE EXTENSION IF NOT EXISTS postgis SCHEMA postgis;'
psql -U postgres -d ekylibre_test -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp" SCHEMA postgis;'
psql -U postgres -d ekylibre_test -c 'CREATE EXTENSION IF NOT EXISTS "unaccent" SCHEMA postgis;'

cp -f test/ci/database.yml config/database.yml

gpg --import 'test/fixture-files/my-private-key.asc'

echo "GPG keys list:"
gpg --list-keys

bundle exec rake db:migrate RAILS_ENV=test VERBOSE=false
