#!/bin/bash

sudo apt-get update -qq

echo ""
echo "--------------------------------------------------------------------------------"
echo "Install packages:"

# Force stop to prevent conflict with existing PostgreSQL
sudo /etc/init.d/postgresql stop

# Install needed packages including PostgreSQL
echo "Removing old Postgres versions."
sudo apt-get remove postgresql-client-9.1 postgresql-client-9.2 postgresql-client-9.3 postgresql-client-9.4 postgresql-client-9.5
echo""
echo "Dependencies install..."
echo""
gem uninstall rgeo
sudo apt-get install -f -qq postgresql-9.6-postgis-2.3 graphicsmagick tesseract-ocr tesseract-ocr-fra tesseract-ocr-eng tesseract-ocr-spa pdftk libreoffice poppler-utils poppler-data qt5-default libqt5webkit5-dev gstreamer1.0-x gstreamer1.0-tools gstreamer1.0-plugins-base libgeos-3.4.2 libproj-dev
gem install rgeo -- --with-geos-dir=/usr/lib --with-proj-dir=/usr/lib
echo ""
echo "Dependencies installed!"
echo ""

echo ""
echo ""
echo ""
echo "--- PROJ4 DEBUGGING ---"
# sudo ln -s /usr/lib/libproj.so.0 /usr/lib/libproj.so.9
# sudo ln -s /usr/lib/libproj.so.0.7.8 /usr/lib/libproj.so.9.1.0
echo "$(which proj)"
echo "$(find /usr/ | grep libproj.so)"
echo "$(which geos)"
echo "$(find /usr/ | grep libgeos.so)"
echo "--- PROJ4 DEBUGGING ---"
echo ""
echo ""
echo ""

# Configure PostgreSQL port to 5432
sudo sed -i -r 's/port\s*=\s*[0-9]+/port = 5432/g' /etc/postgresql/9.6/main/postgresql.conf

# Grant access to all
sudo sed -i '1i local all all trust' /etc/postgresql/9.6/main/pg_hba.conf

# Force PostgreSQL restart
sudo /etc/init.d/postgresql stop
sudo /etc/init.d/postgresql start 9.6
