#!/bin/bash
# Integration
curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash

# Database
psql -U postgres -c "CREATE DATABASE ekylibre_test;"
psql -U postgres -d ekylibre_test -c "CREATE SCHEMA postgis;"
psql -U postgres -d ekylibre_test -c "CREATE EXTENSION postgis;"

cp -f test/ci/database.yml config/database.yml

bundle exec rake db:migrate