#!/bin/bash
psql -U postgres -c "CREATE DATABASE ekylibre_test;"
psql -U postgres -d ekylibre_test -c "CREATE SCHEMA postgis;"
psql -U postgres -d ekylibre_test -c "CREATE EXTENSION postgis SCHEMA postgis;"

cp -f test/ci/database.yml config/database.yml

bundle exec rake db:migrate RAILS_ENV=test
