#!/bin/bash
(
    cd /app

    until nc -z -v -w30 ${POSTGRES_HOST} 5432
    do
      echo 'Waiting for PostgreSQL...'
      sleep 1
    done
    echo "PostgreSQL is up and running"

    psql -h ${POSTGRES_HOST} -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'CREATE SCHEMA IF NOT EXISTS postgis; DROP EXTENSION postgis CASCADE;'
    psql -h ${POSTGRES_HOST} -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'CREATE EXTENSION IF NOT EXISTS postgis SCHEMA postgis;'
    psql -h ${POSTGRES_HOST} -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp" SCHEMA postgis;'
    psql -h ${POSTGRES_HOST} -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'CREATE EXTENSION IF NOT EXISTS "unaccent" SCHEMA postgis;'

    cp -f test/ci/database.yml config/database.yml

    bundle exec rake db:migrate RAILS_ENV=test VERBOSE=false

    bundle exec rake test
)