#!/bin/bash
set -e

function psql_exec {
  psql -h "${POSTGRES_HOST}" -U "${POSTGRES_USER}" -d "${POSTGRES_DB}" -c "$1"
}

(
    cd /app

    bash test/ci/wait_pg.sh "${POSTGRES_HOST}" "${POSTGRES_USER}" "${POSTGRES_DB}"

    psql_exec 'CREATE SCHEMA IF NOT EXISTS postgis; DROP EXTENSION postgis CASCADE;'
    psql_exec 'CREATE EXTENSION IF NOT EXISTS postgis SCHEMA postgis;'
    psql_exec 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp" SCHEMA postgis;'
    psql_exec 'CREATE EXTENSION IF NOT EXISTS "unaccent" SCHEMA postgis;'

    cp -f test/ci/database.yml config/database.yml

    gpg --import 'test/fixture-files/my-private-key.asc'

    echo "GPG keys list:"
    gpg --list-keys

    bundle exec rake db:migrate RAILS_ENV=test VERBOSE=false

    TESTOPTS="--ekylibre --profile-select ${SELECT:-lower}" bin/rake test:all
)
