# Générateur de schéma mono-base (point 1.6).
#
# Le prototype du point 1.4 a porté trois tables à la main ; celui-ci porte les
# 316, à partir de ce que les points 1.5 et la résolution des références ont
# établi :
#
#   plan.yml        — le plan de chaque table, son type de clé, ses index
#   references.yml  — ce que chaque colonne en `_id` désigne vraiment
#   structure.sql   — les colonnes, telles qu'elles sont aujourd'hui
#
# Il écrit `db/monoschema/schema.sql`, qui se charge dans une base vide. Ce
# n'est pas encore la migration des données — c'est la *forme d'arrivée*, celle
# qu'il faut pouvoir montrer avant d'écrire le moindre `ALTER TABLE` sur une
# base de client.
#
#   rake monoschema:schema        # engendre db/monoschema/schema.sql
#   rake monoschema:schema:build  # le charge dans une base de sonde

module MonoschemaSchema
  OUTPUT_PATH = 'db/monoschema/schema.sql'.freeze
  INPLACE_PATH = 'db/monoschema/schema-inplace.sql'.freeze
  DATABASE = ENV.fetch('MONOSCHEMA_FULL_DATABASE', 'ekylibre_monoschema_full')
  APP_ROLE = 'ekylibre_app'.freeze

  module_function

  def plan
    @plan ||= YAML.load_file(Rails.root.join(MonoschemaPlan::PLAN_PATH))
  end

  def references
    @references ||= YAML.load_file(Rails.root.join(MonoschemaReferences::OUTPUT_PATH))
  end

  def structure
    @structure ||= Rails.root.join('db', 'structure.sql').read
  end

  def target_schema(entry)
    case entry['plane']
    when 'reference' then 'lexicon'
    else 'ekylibre'
    end
  end

  # `full` engendre tout, pour une base neuve. `inplace` laisse le `lexicon`
  # existant tranquille et n'y crée que les cinq tables qui viennent de
  # `public` : c'est la forme qu'attend une migration menée dans la base du
  # client, à côté des schémas par ferme.
  def scope
    ENV.fetch('SCOPE', 'full')
  end

  def kept
    @kept ||= plan.reject do |_table, entry|
      next true if entry['plane'] == 'drop'
      next false unless scope == 'inplace'

      entry['plane'] == 'reference' && entry['schema'] == 'lexicon'
    end
  end

  # --- Colonnes ------------------------------------------------------------

  def column_lines(table, entry)
    body = structure[/CREATE TABLE #{entry['schema']}\.#{table} \((.*?)\n\);/m, 1]
    body.strip.lines.filter_map do |line|
      line = line.strip.chomp(',')
      next if line.empty? || line.start_with?('CONSTRAINT')

      rewrite_column(table, entry, line)
    end
  end

  def rewrite_column(table, entry, line)
    name = line[/\A"?([a-z_0-9]+)"?\s/, 1]
    return line if name.nil?
    return id_column(entry) if name == 'id'

    type = target_type(table, name)
    return line if type.nil?

    line.sub(/\A("?#{name}"?)\s+\S+/, "\\1 #{type}")
  end

  def id_column(entry)
    entry['id'] == 'uuid' ? 'id uuid DEFAULT uuidv7() NOT NULL' : 'id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL'
  end

  # Une colonne qui désigne une ligne prend le type de la clé visée. C'est ici
  # que la décision de l'ADR-003 se propage : `interventions.id` passant en
  # uuid, les mille colonnes qui le désignent suivent.
  def target_type(table, column)
    target = references.dig(table, column, 'target')
    return nil if target.nil? || target == 'polymorphe'

    entry = plan[target]
    return nil if entry.nil? || entry['plane'] != 'data'

    entry['id'] == 'uuid' ? 'uuid' : 'bigint'
  end

  # --- Tables --------------------------------------------------------------

  def table_definition(table, entry)
    schema = target_schema(entry)
    columns = column_lines(table, entry)
    columns.unshift('tenant_id uuid NOT NULL') if entry['plane'] == 'data'
    constraints = [primary_key_constraint(table, entry)].compact

    <<~SQL
      CREATE TABLE #{schema}.#{table} (
          #{(columns + constraints).join(",\n    ")}
      );

    SQL
  end

  def primary_key_constraint(table, entry)
    return nil if entry['primary_key'].nil?

    key = entry['plane'] == 'data' ? "tenant_id, #{entry['primary_key'].join(', ')}" : entry['primary_key'].join(', ')
    "CONSTRAINT #{table}_pkey PRIMARY KEY (#{key})"
  end

  # --- Index ---------------------------------------------------------------

  def table_indexes(table, entry)
    schema = target_schema(entry)
    prefix = entry['plane'] == 'data'
    out = +''

    structure.scan(/^CREATE (UNIQUE )?INDEX (\S+) ON #{entry['schema']}\.#{table} USING (\w+) \((.*)\);$/) do |unique, name, method, columns|
      next if method != 'btree' || columns.include?('(')

      columns = "tenant_id, #{columns}" if prefix
      out << "CREATE #{'UNIQUE ' if unique}INDEX #{name} ON #{schema}.#{table} USING btree (#{columns});\n"
    end

    entry['geometry'].each do |column|
      # btree_gist rend le couple possible : sans lui, un index GiST ne sait pas
      # indexer un uuid.
      columns = prefix ? "tenant_id, #{column}" : column
      out << "CREATE INDEX index_#{table}_on_#{column}_gist ON #{schema}.#{table} USING gist (#{columns});\n"
    end

    out
  end

  # --- Clés étrangères -----------------------------------------------------
  #
  # Posées après toutes les tables : le graphe des références a des cycles, et
  # une table se désigne parfois elle-même.
  def foreign_keys(table, entry)
    return '' unless entry['plane'] == 'data'

    references.fetch(table, {}).filter_map do |column, reference|
      target = reference['target']
      next if target.nil? || target == 'polymorphe'

      target_entry = kept[target]
      next if target_entry.nil? || target_entry['primary_key'].nil?

      foreign_key(table, column, target, target_entry)
    end.join
  end

  def foreign_key(table, column, target, target_entry)
    name = "fk_#{table}_#{column}"
    if target_entry['plane'] == 'data'
      <<~SQL
        ALTER TABLE ekylibre.#{table} ADD CONSTRAINT #{name}
            FOREIGN KEY (tenant_id, #{column}) REFERENCES ekylibre.#{target} (tenant_id, id);
      SQL
    else
      # La cible n'a pas de tenant_id : la clé reste simple. C'est le cas des
      # cinq tables passées au référentiel, `units` en tête.
      <<~SQL
        ALTER TABLE ekylibre.#{table} ADD CONSTRAINT #{name}
            FOREIGN KEY (#{column}) REFERENCES #{target_schema(target_entry)}.#{target} (id);
      SQL
    end
  end

  # --- Vues ----------------------------------------------------------------
  #
  # Une vue s'exécute par défaut avec les droits de son propriétaire, et le
  # propriétaire n'est pas soumis aux politiques de ses tables : mesuré sur la
  # sonde, une vue ordinaire rend au rôle applicatif les lignes des *deux*
  # fermes. `security_invoker` (PostgreSQL 15+) la fait s'exécuter avec les
  # droits de l'appelant, et l'isolation revient.
  def views
    out = +"\n-- Vues. `security_invoker` n'est pas une option de confort :\n" \
           "-- sans elle, la vue contourne la Row Level Security de ses tables.\n"
    view_definitions.each do |name, body|
      out << "CREATE VIEW ekylibre.#{name} WITH (security_invoker = true) AS\n#{rewrite_body(body)};\n\n"
    end
    out
  end

  # Les vues matérialisées ne sont **pas** engendrées, et ce n'est pas un oubli.
  # Deux raisons, dont la seconde est la plus grave :
  #
  #   — PostgreSQL n'applique pas la RLS à une vue matérialisée : ses lignes
  #     sont déjà calculées, toutes fermes confondues, et quiconque a le droit
  #     de la lire les lit toutes ;
  #   — surtout, leur regroupement ne porte pas `tenant_id`.
  #     `worker_time_indicators` regroupe par `worker_id` ; en mono-base, deux
  #     fermes ont chacune leur travailleur n° 1, et leurs heures se
  #     retrouveraient **additionnées dans la même ligne**. Ce n'est plus une
  #     fuite, c'est un chiffre faux.
  #
  # Les trois demandent donc d'être réécrites à la main pour porter et regrouper
  # par `tenant_id`, ce qu'aucune réécriture mécanique ne peut faire sur des
  # requêtes de cinquante à cent lignes. `worker_time_indicators` pose en plus
  # une question de coût : elle est rafraîchie à chaque sauvegarde
  # d'intervention, et un `REFRESH` en mono-base recalcule *toutes* les fermes.
  def materialized_views
    <<~SQL

      -- Les trois vues matérialisées — worker_time_indicators,
      -- economic_indicators, incoming_harvest_indicators — ne sont pas reprises
      -- ici : leur regroupement ne porte pas tenant_id, et la RLS ne s'applique
      -- pas à une vue matérialisée. Voir db/monoschema/README.md.
    SQL
  end

  def view_definitions
    @view_definitions ||= ordered(structure.scan(/^CREATE VIEW public\.(\w+) AS\n(.*?);\n/m))
  end

  # Une vue peut en lire une autre : on les pose dans l'ordre de leurs
  # dépendances, sinon la seconde ne trouve pas la première.
  def ordered(definitions)
    names = definitions.map(&:first)
    sorted = []
    remaining = definitions.dup
    until remaining.empty?
      ready, remaining = remaining.partition do |name, body|
        (names - sorted.map(&:first) - [name]).none? { |other| body.match?(/\b#{other}\b/) }
      end
      break if ready.empty?

      sorted.concat(ready)
    end
    sorted + remaining
  end

  # Les corps viennent de `public` ; les tables sont désormais dans `ekylibre`,
  # le référentiel dans `lexicon`. Les vues matérialisées y gagnent leur
  # `tenant_id`, que le regroupement doit porter.
  def rewrite_body(body)
    body.gsub(/\bpublic\.(\w+)/) do
      table = Regexp.last_match(1)
      entry = plan[table]
      schema = entry.nil? ? 'ekylibre' : target_schema(entry)
      "#{schema}.#{table}"
    end
  end

  # --- Isolation -----------------------------------------------------------

  # La lecture peut s'élargir, l'écriture jamais.
  #
  # `USING` accepte, en plus de la ferme courante, celles que `app.tenant_ids`
  # énumère : c'est le chemin inter-fermes du point 1.22 — tableau de bord de
  # CUMA, comparaison de marges, vue coopérative. Il reste *dans* la politique,
  # au lieu de la contourner par un rôle `BYPASSRLS`, si bien qu'une ferme non
  # citée reste invisible même à ce chemin-là.
  #
  # `WITH CHECK` ne connaît, lui, que la ferme courante : on lit chez le
  # voisin, on n'y écrit pas.
  def row_level_security(table)
    <<~SQL
      ALTER TABLE ekylibre.#{table} ENABLE ROW LEVEL SECURITY;
      ALTER TABLE ekylibre.#{table} FORCE ROW LEVEL SECURITY;
      CREATE POLICY tenant_isolation ON ekylibre.#{table}
          USING (tenant_id = ANY (ekylibre.readable_tenants()))
          WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
    SQL
  end

  # --- Assemblage ----------------------------------------------------------

  def build
    data = kept.select { |_table, entry| entry['plane'] == 'data' }
    out = +header
    out << tenants_table
    out << shared_tenants_function
    kept.each { |table, entry| out << table_definition(table, entry) }
    out << "-- Index\n"
    kept.each { |table, entry| out << table_indexes(table, entry) }
    out << "\n-- Clés étrangères\n"
    kept.each { |table, entry| out << foreign_keys(table, entry) }
    out << "\n-- Row Level Security\n"
    data.each_key { |table| out << row_level_security(table) }
    out << views
    out << materialized_views
    out << grants

    path = Rails.root.join(scope == 'full' ? OUTPUT_PATH : INPLACE_PATH)
    path.write(out)
    { path: path.relative_path_from(Rails.root), tables: kept.size, data: data.size, lines: out.lines.count }
  end

  def header
    <<~SQL
      -- ENGENDRÉ PAR `rake monoschema:schema` — NE PAS MODIFIER À LA MAIN.
      --
      -- Forme d'arrivée du mono-schéma : toutes les tables du plan de données
      -- portent `tenant_id`, une clé primaire composite et la Row Level
      -- Security ; le référentiel vit dans `lexicon`, le plan de contrôle et les
      -- données dans `ekylibre`, les extensions dans `postgis`.
      --
      -- Ce fichier ne migre rien : il montre où l'on va. Les migrations de
      -- données — fusion des schémas par ferme, renumérotation des clés,
      -- déduplication des cinq tables qui passent au référentiel — viennent
      -- après, et sur cette cible.

      CREATE SCHEMA IF NOT EXISTS ekylibre;
      CREATE SCHEMA IF NOT EXISTS lexicon;
      CREATE EXTENSION IF NOT EXISTS btree_gist;
      SET search_path TO ekylibre, lexicon, public, postgis;

    SQL
  end

  # Les fermes qu'un chemin inter-fermes a le droit d'ouvrir. La fonction est
  # `STABLE` et lit un réglage de session : elle rend un tableau vide quand
  # personne n'a rien ouvert, ce qui referme la politique par défaut.
  # Qui a le droit d'agréger qui, et pour quoi — puis la fonction qui s'en
  # sert. Dans cet ordre : PostgreSQL valide le corps d'une fonction SQL à sa
  # création, et il y lit déjà la table.
  def shared_tenants_function
    <<~SQL
      -- Le plan de contrôle du chemin inter-fermes (point 1.22). Une ferme
      -- n'entre dans l'agrégation d'une autre que si elle y figure.
      CREATE TABLE ekylibre.tenant_shares (
          id uuid DEFAULT uuidv7() NOT NULL,
          consumer_tenant_id uuid NOT NULL REFERENCES ekylibre.tenants (id),
          shared_tenant_id uuid NOT NULL REFERENCES ekylibre.tenants (id),
          purpose character varying NOT NULL,
          created_at timestamp(6) without time zone DEFAULT now() NOT NULL,
          CONSTRAINT tenant_shares_pkey PRIMARY KEY (id),
          CONSTRAINT tenant_shares_unicity UNIQUE (consumer_tenant_id, shared_tenant_id, purpose)
      );

      -- Les fermes lisibles : la ferme courante, plus celles que le chemin
      -- inter-fermes demande *et* que le plan de contrôle autorise.
      -- L'application ne peut donc pas s'ouvrir une ferme qui n'a pas
      -- consenti, même en posant le réglage elle-même.
      --
      -- Une seule fonction, qui rend un tableau : la politique s'écrit alors
      -- `tenant_id = ANY (…)`, une condition que le planificateur sait porter
      -- sur un index. Écrite en `OR` — ferme courante OU fermes partagées —
      -- elle produisait un `BitmapOr` qui rejetait le prédicat spatial en
      -- filtre : 1 920 lignes écartées après coup au lieu d'un parcours GiST.
      -- Mesuré, puis corrigé.
      CREATE FUNCTION ekylibre.readable_tenants() RETURNS uuid[]
      LANGUAGE sql STABLE AS $$
        SELECT COALESCE(ARRAY(
          SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid
           WHERE NULLIF(current_setting('app.tenant_id', true), '') IS NOT NULL
          UNION
          SELECT s.shared_tenant_id
            FROM ekylibre.tenant_shares s
           WHERE s.consumer_tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
             AND s.shared_tenant_id = ANY (
               COALESCE(string_to_array(NULLIF(current_setting('app.tenant_ids', true), ''), ',')::uuid[],
                        ARRAY[]::uuid[])
             )
        ), ARRAY[]::uuid[])
      $$;

    SQL
  end

  def tenants_table
    <<~SQL
      -- Plan de contrôle minimal : le point 1.14 lui ajoutera `users` et
      -- `user_tenants`.
      CREATE TABLE ekylibre.tenants (
          id uuid DEFAULT uuidv7() NOT NULL,
          slug character varying NOT NULL,
          created_at timestamp(6) without time zone DEFAULT now() NOT NULL,
          updated_at timestamp(6) without time zone DEFAULT now() NOT NULL,
          CONSTRAINT tenants_pkey PRIMARY KEY (id),
          CONSTRAINT tenants_slug_key UNIQUE (slug)
      );

    SQL
  end

  def grants
    <<~SQL

      -- Le rôle applicatif n'est pas propriétaire : il ne peut ni modifier le
      -- schéma, ni désactiver une politique.
      GRANT USAGE ON SCHEMA ekylibre, lexicon, public, postgis TO #{APP_ROLE};
      GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ekylibre TO #{APP_ROLE};
      GRANT SELECT ON ALL TABLES IN SCHEMA lexicon TO #{APP_ROLE};
      GRANT SELECT ON ekylibre.tenants, ekylibre.tenant_shares TO #{APP_ROLE};
      GRANT EXECUTE ON FUNCTION ekylibre.readable_tenants() TO #{APP_ROLE};
      -- Et surtout pas sur les vues matérialisées, qui portent toutes les
      -- fermes : le `GRANT` ci-dessus vise les tables, pas les matviews.
      REVOKE ALL ON ALL TABLES IN SCHEMA ekylibre FROM PUBLIC;
    SQL
  end

  # --- Base de sonde -------------------------------------------------------

  def build_database
    MonoschemaPrototype.exec_sql('postgres', "DROP DATABASE IF EXISTS #{DATABASE}")
    MonoschemaPrototype.exec_sql('postgres', "CREATE DATABASE #{DATABASE}")
    MonoschemaPrototype.exec_sql(DATABASE, 'CREATE SCHEMA IF NOT EXISTS postgis')
    MonoschemaPrototype.exec_sql(DATABASE, 'CREATE EXTENSION IF NOT EXISTS postgis SCHEMA postgis')
    MonoschemaPrototype.exec_sql(DATABASE, 'CREATE EXTENSION IF NOT EXISTS btree_gist SCHEMA public')
    MonoschemaPrototype.exec_sql(DATABASE, <<~SQL)
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '#{APP_ROLE}') THEN
          CREATE ROLE #{APP_ROLE} LOGIN PASSWORD '#{APP_ROLE}';
        END IF;
      END
      $$;
    SQL
    MonoschemaPrototype.psql(DATABASE, ['-f', Rails.root.join(OUTPUT_PATH).to_s])
    # Sans ce marquage, la RLS écarte le prédicat spatial de l'index : mesuré au
    # point 1.4, 63 380 contre 229 en coût estimé. C'est une décision de
    # sécurité, prise ici pour la sonde — le lot 1 la prendra pour de bon.
    MonoschemaPrototype.mark_spatial_operators_leakproof(DATABASE)
  end
end

namespace :monoschema do
  desc 'Engendre db/monoschema/schema.sql — la forme d’arrivée du mono-schéma'
  task schema: :environment do
    result = MonoschemaSchema.build
    puts "#{result[:path]} engendré : #{result[:tables]} tables " \
         "(#{result[:data]} au plan de données), #{result[:lines]} lignes."
  end

  namespace :schema do
    desc 'Charge db/monoschema/schema.sql dans une base de sonde'
    task build: :environment do
      MonoschemaSchema.build_database
      puts "Base #{MonoschemaSchema::DATABASE} chargée."
    end
  end
end
