#!/bin/bash

$RUBYGEMS_DIR = /tmp/rubygems-1.2.0
$GEM = phusion passenger
 
cd $RUBYGEMS_DIR

if [! -e /usr/bin/gem ]
 then 
    if [ ! `ruby setup.rb --no-format-executable --no-rdoc`] 
	then
   		echo -n "Rubygems installation failed: impossible to execute setup.rb"; 
		exit 0;
    fi
fi

rm -R $RUBYGEMS_DIR
gem install -y $GEM
