#!/bin/bash
app=$BUILD_APP
version=$BUILD_VERSION
log=$BUILD_LOG

release=${app}-${version}

rm -fr packages
mkdir -p packages

# dh_make -i -c gpl3 -n -e brice.texier@ekylibre.org -p ${app}_${version}

debdir="`pwd`/debian"

root="`pwd`/files"
rm -fr $root
mkdir -p $root

ln -s $debdir $root/debian

control=$debdir/control

pushd $BUILD_DIR
echo "Rails.application.config.action_controller.relative_url_root = '/ekylibre'" > config/initializers/relative_url_root.rb
bundle install --quiet
echo "production:" > config/database.yml
echo "  adapter: postgis" >> config/database.yml
# echo "  database: db/production.sqlite3" >> config/database.yml
rake assets:precompile RAILS_ENV=production
popd

rm -f  $BUILD_DIR/config/database.yml

cd $root
# dpkg --build $root
dpkg-buildpackage -us -uc -b >> $log

cd ..

# rm -fr copy
# rm -fr $root

mv ${app}_*.deb $BUILD_RELEASE/