#!/bin/sh

controller=$1
old=$2
new=$3

if [ -e "app/controllers/${controller}_controller.rb" ]; then
    echo "$1: $2 -> $3"
else
    echo "Controller $1 is unvalid!"
    exit
fi

replace () {
    for file in `ls $1`
    do rm -f $file.tmp
	sed -r 's/'"$2"'/'"$3"'/g' < $file > $file.tmp
	mv $file.tmp $file
    done
}

move () {
    if [ -e $1 ]; then
	for file in `ls $1`
	do svn mv --force $file $2
	done
    fi
}

rename() {
    controller=$1
    old=$2
    new=$3
    replace "app/controllers/${controller}_controller.rb" "def ${old}(\W|$)" "def ${new}\1"
    replace "app/controllers/*.rb" ":${old}(\W|$)" ":${new}\1"
    replace "app/views/*/*.haml" ":${old}(\W|$)" ":${new}\1"
    replace "app/helpers/*.rb" ":${old}(\W|$)" ":${new}\1"
    replace "config/locales/*/*.yml" "(\W|^)${old}:" "\1${new}:"
    replace "config/rights.yml" " ${old}" " ${new}"
    replace "config/rights.yml" "::${old}" "::${new}"
    move "app/views/$controller/$old.html.haml" "app/views/$controller/$new.html.haml"
    move "app/views/$controller/$old.rjs" "app/views/$controller/$new.rjs"
    for locale in `ls config/locales/` ; do
	move "config/locales/${locale}/help/$controller-$old.txt" "config/locales/${locale}/help/$controller-$new.txt"
	move "config/locales/${locale}/help/$controller-${old}s.txt" "config/locales/${locale}/help/$controller-${new}s.txt"
    done
    
}

rename $controller $old $new


