#!/bin/sh
controller=$1
old=$2
new=$3

replace () {
    for file in `ls $1`
    do rm -f $file.tmp
	sed 's/'"$2"'/'"$3"'/g' < $file > $file.tmp
	mv $file.tmp $file
    done
}

#./rename_action $controller "${old}_display" "${new}"
./rename_action $controller "${old}_create" "${new}_create"
./rename_action $controller "${old}_update" "${new}_update"
./rename_action $controller "${old}_delete" "${new}_delete"
./rename_action $controller "${old}_delete" "${new}_close"
./rename_action $controller "${old}_print" "${new}_print"
./rename_action $controller "${old}_up" "${new}_up"
./rename_action $controller "${old}_down" "${new}_down"
#./rename_action $controller "${old}_mail" "${new}_mail"
#./rename_action $controller "${old}_extract" "${new}_extract"
#./rename_action $controller "${old}_close" "${new}_close"
#./rename_action $controller "${old}_point" "${new}_point"
#./rename_action $controller "${old}_letter" "${new}_letter"
./rename_action $controller "${old}_increment" "${new}_increment"
./rename_action $controller "${old}_decrement" "${new}_decrement"
./rename_action $controller "${old}_lock" "${new}_lock"
./rename_action $controller "${old}_unlock" "${new}_unlock"
svn mv --force app/views/${controller}/_${old}_form.html.haml app/views/${controller}/_${new}_form.html.haml
svn mv --force app/views/${controller}/${old}.html.haml app/views/${controller}/${new}.html.haml
svn mv --force app/views/${controller}/${old}s.html.haml app/views/${controller}/${new}s.html.haml
# replace "config/locales/*/*.${controller}.yml" "_${old}_form:" "_${new}_form:"
