#!/bin/sh
controller=$1
old=$2
new=$3

replace () {
    for file in `ls $1`
    do rm -f $file.tmp
	sed 's/'"$2"'/'"$3"'/g' < $file > $file.tmp
	mv $file.tmp $file
    done
}

#./rename_action.sh $controller "${old}_display" "${new}"
#./rename_action.sh $controller "${old}_create" "${new}_create"
#./rename_action.sh $controller "${old}_update" "${new}_update"
#./rename_action.sh $controller "${old}_delete" "${new}_delete"
#./rename_action.sh $controller "${old}_print" "${new}_print"
#./rename_action.sh $controller "${old}_up" "${new}_up"
#./rename_action.sh $controller "${old}_down" "${new}_down"
#./rename_action.sh $controller "${old}_mail" "${new}_mail"
#./rename_action.sh $controller "${old}_extract" "${new}_extract"
#./rename_action.sh $controller "${old}_close" "${new}_close"
#./rename_action.sh $controller "${old}_point" "${new}_point"
#./rename_action.sh $controller "${old}_letter" "${new}_letter"
#./rename_action.sh $controller "${old}_increment" "${new}_increment"
#./rename_action.sh $controller "${old}_decrement" "${new}_decrement"
#./rename_action.sh $controller "${old}_lock" "${new}_lock"
#./rename_action.sh $controller "${old}_unlock" "${new}_unlock"
svn mv --force app/views/${controller}/_${old}_form.html.haml app/views/${controller}/_${new}_form.html.haml
replace "config/locales/*.${controller}.yml" "_${old}_form:" "_${new}_form:"
