source "http://rubygems.org"

gem "rails", "2.3.10"
gem "i18n", "0.4.2"
gem "haml" # , "~2"
gem "fastercsv", :platforms=>[:ruby_18, :mri_18]
gem "libxml-ruby", "1.1.3", :require=>"libxml"
gem "rubyzip", :require=>"zip/zip"
gem "will_paginate", "~> 2.3"
gem "state_machine", :path => "vendor/ogems/state_machine-0.9.4"
# gem "ruby-graphviz", ">= 0.9.0"
# gem "exception_notification", :path => "vendor/ogems/exception_notification-2.3.3.0", :require=>"exception_notifier"

# gem "ruby-debug"

group :test do
  gem "thoughtbot-shoulda", :require => "shoulda"
end  

# gem "sqlite3-ruby", :require => "sqlite3", :platforms=>[:ruby_19, :mri_19]
gem "pg", "0.9.0"
gem "mysql"
