#!/bin/sh
# Use it as postgres

user=$1
dbname=$2
password=`< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c32`
# Conf database
count=`psql -q -t -A -c "SELECT count(*) FROM pg_catalog.pg_user WHERE usename='${user}'"`
if [ "${count}" = "0" ]; then
    psql -q -c "CREATE USER ${user} WITH ENCRYPTED PASSWORD '${password}'"
else
    psql -q -c "ALTER USER ${user} WITH ENCRYPTED PASSWORD '${password}'"
fi
count=`psql -q -t -A -c "SELECT count(*) FROM pg_catalog.pg_database WHERE datname='${dbname}'"`
if [ "${count}" = "0" ]; then
    psql -q -c "CREATE DATABASE ${dbname}"
fi
psql -q -c "GRANT ALL ON DATABASE ${dbname} TO ${user}"

echo ${password}