ARG IMAGE_SOURCE


FROM ${IMAGE_SOURCE} AS files
FROM node:alpine AS node
COPY --from=files /app/package.json /app/yarn.lock ./
RUN yarn


FROM ${IMAGE_SOURCE} AS builder
COPY --from=node /node_modules /app/node_modules
COPY database.yml application.yml /app/config/

RUN RAILS_ENV=production bundle exec rake assets:precompile


FROM ${IMAGE_SOURCE}
COPY --from=builder /app/public/assets /app/puclic/
EXPOSE 3000