ARG RUBY_VERSION=2.3

FROM registry.gitlab.com/ekylibre/docker-base-images/ruby${RUBY_VERSION}-prod:master

RUN mkdir /app
WORKDIR /app

CMD ["/app/docker/waitpg", "/app/docker/prod/serve"]

COPY Gemfile Gemfile.lock /app/
RUN BUNDLE_WITHOUT=test:development bundle install -j $(nproc) --path vendor/ruby

COPY . /app
