-- ENGENDRÉ PAR `rake monoschema:generate` — NE PAS MODIFIER À LA MAIN.
--
-- Prototype du point 1.4 : trois tables portées du schéma-par-tenant vers
-- une base unique à `tenant_id`, PK et FK composites, index tenant-aware,
-- RLS `FORCE`. Les colonnes viennent telles quelles de db/structure.sql.
--
-- Les extensions vivent dans `public`, les tables applicatives dans le
-- schéma `ekylibre` (ADR-002, point 5).

CREATE SCHEMA IF NOT EXISTS ekylibre;
SET search_path TO ekylibre, public, postgis;

CREATE TABLE ekylibre.tenants (
    id uuid DEFAULT uuidv7() NOT NULL,
    slug character varying NOT NULL,
    created_at timestamp(6) without time zone DEFAULT now() NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT now() NOT NULL,
    CONSTRAINT tenants_pkey PRIMARY KEY (id),
    CONSTRAINT tenants_slug_key UNIQUE (slug)
);

CREATE TABLE ekylibre.interventions (
    tenant_id uuid NOT NULL REFERENCES ekylibre.tenants (id),
    id uuid DEFAULT uuidv7() NOT NULL,
    issue_id integer,
    prescription_id integer,
    procedure_name character varying NOT NULL,
    state character varying NOT NULL,
    started_at timestamp without time zone NOT NULL,
    stopped_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    creator_id integer,
    updater_id integer,
    lock_version integer DEFAULT 0 NOT NULL,
    event_id integer,
    number character varying,
    description text,
    working_duration integer NOT NULL,
    whole_duration integer NOT NULL,
    actions character varying,
    custom_fields jsonb,
    nature character varying NOT NULL,
    request_intervention_id uuid,
    trouble_encountered boolean DEFAULT false NOT NULL,
    trouble_description text,
    accounted_at timestamp without time zone,
    currency character varying,
    journal_entry_id integer,
    request_compliant boolean,
    auto_calculate_working_periods boolean DEFAULT false,
    intervention_proposal_id integer,
    parent_id uuid,
    purchase_id integer,
    costing_id integer,
    validator_id integer,
    providers jsonb,
    provider jsonb,
    name character varying,
    weather_conditions jsonb,
    early_reentry boolean DEFAULT false NOT NULL,
    early_reentry_ppe_description text,
    early_reentry_reason text,
    beneficiary_siret character varying,
    CONSTRAINT interventions_pkey PRIMARY KEY (tenant_id, id)
);

CREATE TABLE ekylibre.intervention_parameters (
    tenant_id uuid NOT NULL REFERENCES ekylibre.tenants (id),
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    intervention_id uuid NOT NULL,
    product_id bigint,
    variant_id integer,
    quantity_population numeric(19,4),
    working_zone postgis.geometry(MultiPolygon,4326),
    reference_name character varying NOT NULL,
    "position" integer NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    creator_id integer,
    updater_id integer,
    lock_version integer DEFAULT 0 NOT NULL,
    event_participation_id integer,
    outcoming_product_id integer,
    type character varying,
    new_container_id integer,
    new_group_id integer,
    new_variant_id integer,
    quantity_handler character varying,
    quantity_value numeric(19,4),
    quantity_unit_name character varying,
    quantity_indicator_name character varying,
    group_id bigint,
    new_name character varying,
    component_id integer,
    assembly_id integer,
    currency character varying,
    unit_pretax_stock_amount numeric(19,4) DEFAULT 0.0 NOT NULL,
    dead boolean DEFAULT false NOT NULL,
    identification_number character varying,
    batch_number character varying,
    usage_id character varying,
    allowed_entry_factor interval,
    allowed_harvest_factor interval,
    imputation_ratio numeric(19,4) DEFAULT 1 NOT NULL,
    reference_data jsonb DEFAULT '{}'::jsonb,
    using_live_data boolean DEFAULT true,
    applications_frequency interval,
    specie_variety jsonb DEFAULT '{}'::jsonb,
    working_zone_area_value numeric(19,4),
    spray_volume_value numeric(19,4),
    phenological_bbch_stage integer,
    application_mode character varying,
    CONSTRAINT intervention_parameters_pkey PRIMARY KEY (tenant_id, id)
);

CREATE TABLE ekylibre.products (
    tenant_id uuid NOT NULL REFERENCES ekylibre.tenants (id),
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type character varying,
    name character varying NOT NULL,
    number character varying NOT NULL,
    variant_id integer NOT NULL,
    nature_id integer NOT NULL,
    category_id integer NOT NULL,
    initial_born_at timestamp without time zone,
    initial_dead_at timestamp without time zone,
    initial_container_id integer,
    initial_owner_id integer,
    initial_enjoyer_id integer,
    initial_population numeric(19,4) DEFAULT 0.0,
    initial_shape postgis.geometry(MultiPolygon,4326),
    initial_father_id integer,
    initial_mother_id integer,
    variety character varying NOT NULL,
    derivative_of character varying,
    tracking_id integer,
    fixed_asset_id integer,
    born_at timestamp without time zone,
    dead_at timestamp without time zone,
    description text,
    identification_number character varying,
    work_number character varying,
    address_id integer,
    parent_id bigint,
    default_storage_id integer,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    creator_id integer,
    updater_id integer,
    lock_version integer DEFAULT 0 NOT NULL,
    person_id integer,
    initial_geolocation postgis.geometry(Point,4326),
    uuid uuid,
    initial_movement_id integer,
    custom_fields jsonb,
    team_id integer,
    member_variant_id integer,
    birth_date_completeness character varying,
    birth_farm_number character varying,
    country character varying,
    filiation_status character varying,
    first_calving_on timestamp without time zone,
    mother_country character varying,
    mother_variety character varying,
    mother_identification_number character varying,
    father_country character varying,
    father_variety character varying,
    father_identification_number character varying,
    origin_country character varying,
    origin_identification_number character varying,
    end_of_life_reason character varying,
    originator_id integer,
    codes jsonb,
    reading_cache jsonb DEFAULT '{}'::jsonb,
    activity_production_id integer,
    conditioning_unit_id integer,
    type_of_occupancy character varying,
    specie_variety jsonb DEFAULT '{}'::jsonb,
    provider jsonb DEFAULT '{}'::jsonb,
    isacompta_analytic_code character varying(2),
    worker_group_item_id integer,
    with_easement_capacity boolean DEFAULT false NOT NULL,
    easement_capacity_variety character varying,
    certiphyto_number character varying,
    certiphyto_kind character varying,
    certiphyto_expires_on date,
    CONSTRAINT products_pkey PRIMARY KEY (tenant_id, id)
);

-- Index de interventions, tous préfixés par tenant_id.
CREATE INDEX index_interventions_on_created_at ON ekylibre.interventions USING btree (tenant_id, created_at);
CREATE INDEX index_interventions_on_creator_id ON ekylibre.interventions USING btree (tenant_id, creator_id);
CREATE INDEX index_interventions_on_event_id ON ekylibre.interventions USING btree (tenant_id, event_id);
CREATE INDEX index_interventions_on_intervention_proposal_id ON ekylibre.interventions USING btree (tenant_id, intervention_proposal_id);
CREATE INDEX index_interventions_on_issue_id ON ekylibre.interventions USING btree (tenant_id, issue_id);
CREATE INDEX index_interventions_on_journal_entry_id ON ekylibre.interventions USING btree (tenant_id, journal_entry_id);
CREATE INDEX index_interventions_on_nature ON ekylibre.interventions USING btree (tenant_id, nature);
CREATE INDEX index_interventions_on_prescription_id ON ekylibre.interventions USING btree (tenant_id, prescription_id);
CREATE INDEX index_interventions_on_procedure_name ON ekylibre.interventions USING btree (tenant_id, procedure_name);
CREATE INDEX index_interventions_on_purchase_id ON ekylibre.interventions USING btree (tenant_id, purchase_id);
CREATE INDEX index_interventions_on_request_intervention_id ON ekylibre.interventions USING btree (tenant_id, request_intervention_id);
CREATE INDEX index_interventions_on_started_at ON ekylibre.interventions USING btree (tenant_id, started_at);
CREATE INDEX index_interventions_on_stopped_at ON ekylibre.interventions USING btree (tenant_id, stopped_at);
CREATE INDEX index_interventions_on_updated_at ON ekylibre.interventions USING btree (tenant_id, updated_at);
CREATE INDEX index_interventions_on_updater_id ON ekylibre.interventions USING btree (tenant_id, updater_id);

-- Index de intervention_parameters, tous préfixés par tenant_id.
CREATE INDEX index_intervention_parameters_on_assembly_id ON ekylibre.intervention_parameters USING btree (tenant_id, assembly_id);
CREATE INDEX index_intervention_parameters_on_component_id ON ekylibre.intervention_parameters USING btree (tenant_id, component_id);
CREATE INDEX index_intervention_parameters_on_created_at ON ekylibre.intervention_parameters USING btree (tenant_id, created_at);
CREATE INDEX index_intervention_parameters_on_creator_id ON ekylibre.intervention_parameters USING btree (tenant_id, creator_id);
CREATE INDEX index_intervention_parameters_on_event_participation_id ON ekylibre.intervention_parameters USING btree (tenant_id, event_participation_id);
CREATE INDEX index_intervention_parameters_on_group_id ON ekylibre.intervention_parameters USING btree (tenant_id, group_id);
CREATE INDEX index_intervention_parameters_on_int_and_type ON ekylibre.intervention_parameters USING btree (tenant_id, intervention_id, type);
CREATE INDEX index_intervention_parameters_on_intervention_id ON ekylibre.intervention_parameters USING btree (tenant_id, intervention_id);
CREATE INDEX index_intervention_parameters_on_new_container_id ON ekylibre.intervention_parameters USING btree (tenant_id, new_container_id);
CREATE INDEX index_intervention_parameters_on_new_group_id ON ekylibre.intervention_parameters USING btree (tenant_id, new_group_id);
CREATE INDEX index_intervention_parameters_on_new_variant_id ON ekylibre.intervention_parameters USING btree (tenant_id, new_variant_id);
CREATE INDEX index_intervention_parameters_on_outcoming_product_id ON ekylibre.intervention_parameters USING btree (tenant_id, outcoming_product_id);
CREATE INDEX index_intervention_parameters_on_pro_and_int_ids ON ekylibre.intervention_parameters USING btree (tenant_id, product_id, intervention_id);
CREATE INDEX index_intervention_parameters_on_pro_and_ref_and_type ON ekylibre.intervention_parameters USING btree (tenant_id, product_id, reference_name, type);
CREATE INDEX index_intervention_parameters_on_pro_and_type ON ekylibre.intervention_parameters USING btree (tenant_id, product_id, type);
CREATE INDEX index_intervention_parameters_on_product_id ON ekylibre.intervention_parameters USING btree (tenant_id, product_id);
CREATE INDEX index_intervention_parameters_on_reference_name ON ekylibre.intervention_parameters USING btree (tenant_id, reference_name);
CREATE INDEX index_intervention_parameters_on_type ON ekylibre.intervention_parameters USING btree (tenant_id, type);
CREATE INDEX index_intervention_parameters_on_updated_at ON ekylibre.intervention_parameters USING btree (tenant_id, updated_at);
CREATE INDEX index_intervention_parameters_on_updater_id ON ekylibre.intervention_parameters USING btree (tenant_id, updater_id);
CREATE INDEX index_intervention_parameters_on_variant_id ON ekylibre.intervention_parameters USING btree (tenant_id, variant_id);
CREATE INDEX index_intervention_parameters_on_tenant_and_working_zone ON ekylibre.intervention_parameters USING gist (tenant_id, working_zone);

-- Index de products, tous préfixés par tenant_id.
CREATE INDEX index_products_on_activity_production_id ON ekylibre.products USING btree (tenant_id, activity_production_id);
CREATE INDEX index_products_on_address_id ON ekylibre.products USING btree (tenant_id, address_id);
CREATE INDEX index_products_on_category_id ON ekylibre.products USING btree (tenant_id, category_id);
CREATE INDEX index_products_on_certiphyto_expires_on ON ekylibre.products USING btree (tenant_id, certiphyto_expires_on);
CREATE INDEX index_products_on_created_at ON ekylibre.products USING btree (tenant_id, created_at);
CREATE INDEX index_products_on_creator_id ON ekylibre.products USING btree (tenant_id, creator_id);
CREATE INDEX index_products_on_default_storage_id ON ekylibre.products USING btree (tenant_id, default_storage_id);
CREATE INDEX index_products_on_fixed_asset_id ON ekylibre.products USING btree (tenant_id, fixed_asset_id);
CREATE INDEX index_products_on_initial_container_id ON ekylibre.products USING btree (tenant_id, initial_container_id);
CREATE INDEX index_products_on_initial_enjoyer_id ON ekylibre.products USING btree (tenant_id, initial_enjoyer_id);
CREATE INDEX index_products_on_initial_father_id ON ekylibre.products USING btree (tenant_id, initial_father_id);
CREATE INDEX index_products_on_initial_mother_id ON ekylibre.products USING btree (tenant_id, initial_mother_id);
CREATE INDEX index_products_on_initial_movement_id ON ekylibre.products USING btree (tenant_id, initial_movement_id);
CREATE INDEX index_products_on_initial_owner_id ON ekylibre.products USING btree (tenant_id, initial_owner_id);
CREATE INDEX index_products_on_member_variant_id ON ekylibre.products USING btree (tenant_id, member_variant_id);
CREATE INDEX index_products_on_name ON ekylibre.products USING btree (tenant_id, name);
CREATE INDEX index_products_on_nature_id ON ekylibre.products USING btree (tenant_id, nature_id);
CREATE UNIQUE INDEX index_products_on_number ON ekylibre.products USING btree (tenant_id, number);
CREATE INDEX index_products_on_originator_id ON ekylibre.products USING btree (tenant_id, originator_id);
CREATE INDEX index_products_on_parent_id ON ekylibre.products USING btree (tenant_id, parent_id);
CREATE INDEX index_products_on_team_id ON ekylibre.products USING btree (tenant_id, team_id);
CREATE INDEX index_products_on_tracking_id ON ekylibre.products USING btree (tenant_id, tracking_id);
CREATE INDEX index_products_on_type ON ekylibre.products USING btree (tenant_id, type);
CREATE INDEX index_products_on_updated_at ON ekylibre.products USING btree (tenant_id, updated_at);
CREATE INDEX index_products_on_updater_id ON ekylibre.products USING btree (tenant_id, updater_id);
CREATE INDEX index_products_on_uuid ON ekylibre.products USING btree (tenant_id, uuid);
CREATE INDEX index_products_on_variant_id ON ekylibre.products USING btree (tenant_id, variant_id);
CREATE INDEX index_products_on_variety ON ekylibre.products USING btree (tenant_id, variety);
CREATE INDEX index_products_on_worker_group_item_id ON ekylibre.products USING btree (tenant_id, worker_group_item_id);
CREATE INDEX index_products_on_tenant_and_initial_shape ON ekylibre.products USING gist (tenant_id, initial_shape);

-- Clés étrangères composites : la référence ne peut pas franchir le tenant.
ALTER TABLE ekylibre.interventions
    ADD CONSTRAINT fk_interventions_request_intervention_id FOREIGN KEY (tenant_id, request_intervention_id)
    REFERENCES ekylibre.interventions (tenant_id, id);
ALTER TABLE ekylibre.interventions
    ADD CONSTRAINT fk_interventions_parent_id FOREIGN KEY (tenant_id, parent_id)
    REFERENCES ekylibre.interventions (tenant_id, id);
ALTER TABLE ekylibre.intervention_parameters
    ADD CONSTRAINT fk_intervention_parameters_intervention_id FOREIGN KEY (tenant_id, intervention_id)
    REFERENCES ekylibre.interventions (tenant_id, id);
ALTER TABLE ekylibre.intervention_parameters
    ADD CONSTRAINT fk_intervention_parameters_product_id FOREIGN KEY (tenant_id, product_id)
    REFERENCES ekylibre.products (tenant_id, id);
ALTER TABLE ekylibre.intervention_parameters
    ADD CONSTRAINT fk_intervention_parameters_group_id FOREIGN KEY (tenant_id, group_id)
    REFERENCES ekylibre.intervention_parameters (tenant_id, id);
ALTER TABLE ekylibre.products
    ADD CONSTRAINT fk_products_parent_id FOREIGN KEY (tenant_id, parent_id)
    REFERENCES ekylibre.products (tenant_id, id);

-- Row Level Security, FORCE comprise (elle seule couvre le proprietaire).
ALTER TABLE ekylibre.interventions ENABLE ROW LEVEL SECURITY;
ALTER TABLE ekylibre.interventions FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON ekylibre.interventions
    USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE ekylibre.intervention_parameters ENABLE ROW LEVEL SECURITY;
ALTER TABLE ekylibre.intervention_parameters FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON ekylibre.intervention_parameters
    USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
ALTER TABLE ekylibre.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE ekylibre.products FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON ekylibre.products
    USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);

-- Le rôle applicatif n'est pas proprietaire : il ne peut ni modifier le
-- schema, ni desactiver une politique.
GRANT USAGE ON SCHEMA ekylibre, public, postgis TO ekylibre_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ekylibre TO ekylibre_app;
-- MAINTAIN (PostgreSQL 17+) pour qu'un ANALYZE reste possible sans etre
-- proprietaire : le prototype en a besoin pour que le planificateur ait
-- des statistiques sur la colonne geometrique.
GRANT MAINTAIN ON ALL TABLES IN SCHEMA ekylibre TO ekylibre_app;
GRANT SELECT ON postgis.spatial_ref_sys TO ekylibre_app;
