require_relative 'exchangers/agro_systemes'
require_relative 'exchangers/bordeaux_sciences_agro'
require_relative 'exchangers/ebp'
require_relative 'exchangers/ekylibre'
require_relative 'exchangers/isagri'
require_relative 'exchangers/telepac'
require_relative 'exchangers/legrain'
