dir = File.join(File.dirname(__FILE__), 'activerecord')
require File.join(dir, 'base')
require File.join(dir, 'migration')
require File.join(dir, 'autosave')
require File.join(dir, 'sums')
require File.join(dir, 'connection_adapters', 'abstract_adapter')
require File.join(dir, 'connection_adapters', 'sqlserver_adapter')
require File.join(dir, 'connection_adapters', 'sqlserver', 'quoting')
# require File.join(dir, 'acts', 'accountable')
require File.join(dir, 'bookkeep')
require File.join(dir, 'acts', 'numbered')
