require File.dirname(__FILE__) + '/safe_string'
require File.dirname(__FILE__) + '/hash_string'
require File.dirname(__FILE__) + '/i18n'
# require File.dirname(__FILE__) + '/active_record'
# require File.dirname(__FILE__) + '/measure/angle'
