# Autogenerated from Ekylibre (`rake clean:models` or `rake clean`)
# List of all models
EKYLIBRE_MODELS = [:account, :account_balance, :contact, :delay, :entity, :entity_category, :entity_link, :entity_link_nature, :entity_nature, :event, :event_nature, :journal, :journal_entry, :journal_record, :sale_order, :sale_order_line, :sale_order_nature, :sale_payment, :sale_payment_mode, :sale_payment_part, :subscription, :subscription_nature, :transfer, :user]

# List of all references
EKYLIBRE_REFERENCES = {
  :account => {
    :company_id => :company,
    :creator_id => :user,
    :updater_id => :user
  },
  :account_balance => {
    :account_id => :account,
    :company_id => :company,
    :creator_id => :user,
    :financialyear_id => :financialyear,
    :updater_id => :user
  },
  :contact => {
    :area_id => :area,
    :company_id => :company,
    :creator_id => :user,
    :entity_id => :entity,
    :updater_id => :user
  },
  :delay => {
    :company_id => :company,
    :creator_id => :user,
    :updater_id => :user
  },
  :entity => {
    :attorney_account_id => :account,
    :category_id => :entity_category,
    :client_account_id => :account,
    :company_id => :company,
    :creator_id => :user,
    :nature_id => :entity_nature,
    :payment_delay_id => :delay,
    :payment_mode_id => :sale_payment_mode,
    :proposer_id => :entity,
    :responsible_id => :user,
    :supplier_account_id => :account,
    :updater_id => :user
  },
  :entity_category => {
    :company_id => :company,
    :creator_id => :user,
    :updater_id => :user
  },
  :entity_link => {
    :company_id => :company,
    :creator_id => :user,
    :entity_1_id => :entity,
    :entity_2_id => :entity,
    :nature_id => :entity_link_nature,
    :updater_id => :user
  },
  :entity_link_nature => {
    :company_id => :company,
    :creator_id => :user,
    :updater_id => :user
  },
  :entity_nature => {
    :company_id => :company,
    :creator_id => :user,
    :updater_id => :user
  },
  :event => {
    :company_id => :company,
    :creator_id => :user,
    :entity_id => :entity,
    :nature_id => :event_nature,
    :responsible_id => :user,
    :updater_id => :user
  },
  :event_nature => {
    :company_id => :company,
    :creator_id => :user,
    :updater_id => :user
  },
  :journal => {
    :company_id => :company,
    :counterpart_id => :account,
    :creator_id => :user,
    :currency_id => :currency,
    :updater_id => :user
  },
  :journal_entry => {
    :account_id => :account,
    :bank_statement_id => :bank_statement,
    :company_id => :company,
    :creator_id => :user,
    :journal_id => :journal,
    :record_id => :journal_record,
    :updater_id => :user
  },
  :journal_record => {
    :company_id => :company,
    :creator_id => :user,
    :currency_id => :currency,
    :journal_id => :journal,
    :resource_id => "resource_type",
    :updater_id => :user
  },
  :sale_order => {
    :client_id => :entity,
    :company_id => :company,
    :contact_id => :contact,
    :creator_id => :user,
    :currency_id => :currency,
    :delivery_contact_id => :contact,
    :expiration_id => :delay,
    :invoice_contact_id => :contact,
    :journal_record_id => :journal_record,
    :nature_id => :sale_order_nature,
    :payment_delay_id => :delay,
    :responsible_id => :user,
    :transporter_id => :entity,
    :updater_id => :user
  },
  :sale_order_line => {
    :account_id => :account,
    :company_id => :company,
    :creator_id => :user,
    :entity_id => :entity,
    :location_id => :location,
    :order_id => :sale_order,
    :price_id => :price,
    :product_id => :product,
    :reduction_origin_id => :sale_order_line,
    :tax_id => :tax,
    :tracking_id => :tracking,
    :unit_id => :unit,
    :updater_id => :user
  },
  :sale_order_nature => {
    :company_id => :company,
    :creator_id => :user,
    :expiration_id => :delay,
    :payment_delay_id => :delay,
    :payment_mode_id => :sale_payment_mode,
    :updater_id => :user
  },
  :sale_payment => {
    :company_id => :company,
    :creator_id => :user,
    :embanker_id => :user,
    :embankment_id => :embankment,
    :journal_record_id => :journal_record,
    :mode_id => :sale_payment_mode,
    :payer_id => :entity,
    :updater_id => :user
  },
  :sale_payment_mode => {
    :cash_id => :cash,
    :commission_account_id => :account,
    :company_id => :company,
    :creator_id => :user,
    :embankables_account_id => :account,
    :updater_id => :user
  },
  :sale_payment_part => {
    :company_id => :company,
    :creator_id => :user,
    :expense_id => "expense_type",
    :journal_record_id => :journal_record,
    :payment_id => :sale_payment,
    :updater_id => :user
  },
  :subscription => {
    :company_id => :company,
    :contact_id => :contact,
    :creator_id => :user,
    :entity_id => :entity,
    :invoice_id => :invoice,
    :nature_id => :subscription_nature,
    :product_id => :product,
    :sale_order_id => :sale_order,
    :sale_order_line_id => :sale_order_line,
    :updater_id => :user
  },
  :subscription_nature => {
    :company_id => :company,
    :creator_id => :user,
    :entity_link_nature_id => :entity_link_nature,
    :updater_id => :user
  },
  :transfer => {
    :company_id => :company,
    :creator_id => :user,
    :journal_record_id => :journal_record,
    :supplier_id => :entity,
    :updater_id => :user
  },
  :user => {
    :company_id => :company,
    :creator_id => :user,
    :department_id => :department,
    :establishment_id => :establishment,
    :profession_id => :profession,
    :role_id => :role,
    :updater_id => :user
  }
}
