#!/bin/sh
app=$BUILD_APP
version=$BUILD_VERSION
log=$BUILD_LOG

source=${app}-${version}-source

cd $BUILD_DIR

if [ -n "`which zip`" ]; then
    echo " * Zip source" >> $log
    zip -r $BUILD_RELEASE/${source}.zip * -x *.svn* log/*.log >> $log
else
    echo " * No zip command. Run 'sudo apt-get install zip'"
    echo " * No zip command. Run 'sudo apt-get install zip'" >> $log
fi

if [ -n "`which tar`" ]; then
    echo " * Gzip source" >> $log
    tar cfvhz $BUILD_RELEASE/${source}.tar.gz  --exclude=.svn --exclude=log/*.log * >> $log
    echo " * Bzip source" >> $log
    tar cfvhj $BUILD_RELEASE/${source}.tar.bz2 --exclude=.svn --exclude=log/*.log * >> $log
else
    echo " * No tar command. Run 'sudo apt-get install tar'"
    echo " * No tar command. Run 'sudo apt-get install tar'" >> $log
fi
