CREATE SCHEMA IF NOT EXISTS postgis;
DROP EXTENSION postgis CASCADE;
CREATE EXTENSION IF NOT EXISTS postgis SCHEMA postgis;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA postgis;
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA postgis;
CREATE EXTENSION IF NOT EXISTS "unaccent" WITH SCHEMA postgis;
CREATE EXTENSION IF NOT EXISTS "pg_trgm" WITH SCHEMA postgis;
