fr_pcga:
  profit_and_loss_statement:
    products_sales: '707 7097 C'
    animal_sales: '704 7094 756 C'
    productions_sales: '701 702 703 705 706 708 7091 7092 7093 7095 7096 7098 C'
    inventory_variations: '712 713 C'
    capitalised_production: '721 722 724 726 C'
    subsidies: '741 742 743 744 745 C'
    provisions_revenues: '781 791 C'
    other_products: '75 C, !756'
    merchandises_purchases: '607 6097 D'
    merchandises_purchases_stocks_variation: '6037 D'
    products_purchases: '601 602 6091 6092 D'
    purchases_stocks_variation: '6031 6032 D'
    animal_purchases: '604 6094 D'
    other_purchases: '605 606 61 62 6095 6096 6098 656 D'
    taxes: '63 D'
    wages: '64 D, !645 !646 !647 !648'
    social_expenses: '645 646 647 648 D'
    depreciations_inputations_expenses: '681 D'
    other_expenses: '65 D, !656'
    products_subtotal: '70 71 72 74 75 781 791 C'
    charges_subtotal: '60 61 62 63 64 65 681'
    exploitation_result: '70 71 72 74 75 781 791 C, - 60 61 62 63 64 65 681'
    financial_participations: '761 C'
    financial_debts: '762 C'
    financial_others_interests: '763 764 765 768 C'
    financial_depreciations: '786 796 C'
    financial_positive_change: '766 C'
    financial_net_cession_values: '767 C'
    financial_products_subtotal: '76 786 796 C'
    financial_asset_dotations: '686 D'
    financial_interests_and_charges: '661 664 665 668 D'
    financial_negative_change: '666 D'
    financial_net_cession_debts: '667 D'
    financial_expenses_subtotal: '66 686 D'
    financial_result: '76 786 796 C, - 66 686'
    before_taxe_result: '70 71 72 74 75 781 791 76 786 796 C, - 60 61 62 63 64 65 681 66 686'
    exceptional_products_on_management_operations: '771 C'
    exceptional_products_on_assets_cessions: '775 C'
    exceptional_products_on_capital_operations: '777 778 C'
    exceptional_products_on_provisions: '787 797 C'
    exceptional_products_subtotal: '77 787 797 C'
    exceptional_expenses_on_management_operations: '671 673 D'
    exceptional_expenses_on_assets_cessions: '675 D'
    exceptional_expenses_on_capital_operations: '678 D'
    exceptional_expenses_on_provisions: '687 D'
    exceptional_expenses_subtotal: '67 687 D'
    exceptional_result: '77 787 797 C, - 67 687'
    employee_involvement: '691 D'
    profit_taxe: '695 697 699 D'
    products_total: '7 C'
    charges_total: '6 D'
    exercice_result: '70 71 72 74 75 781 791 76 786 796 77 787 797 C, - 60 61 62 63 64 65 681 66 686 67 687 691 695 697 699'
  ratio:
    exercice_production: '70 71 72 73 756 C, !707 !7097'
    commercial_margin: '707 7097 C, - 607 6097 6037'
    production_purchases: '601 602 6091 6092 6031 6032 D'
    production_others_charges: '605 606 61 62 6355 6095 6096 6098 D'
    added_value: '70 71 72 73 756 707 7097 C, - 607 6097 6037 601 602 6091 6092 6031 6032 605 606 61 62 6355 6095 6096 6098'
    taxes_and_wages: '63 64 D, !6355'
    subsidies: '742 743 744 745 C'
    operating_margin: '70 71 72 73 756 707 7097 742 743 744 745 C, - 607 6097 6037 601 602 6091 6092 6031 6032 605 606 61 62 6355 6095 6096 6098 63 64'
  balance_sheet:
    unsubcribed_capital: '109'
    incorporeal_assets_creation_costs: '201'
    incorporeal_assets_creation_costs_depreciations: '2801 C'
    incorporeal_assets_others: '203 205 206 207 208'
    incorporeal_assets_others_depreciations: '2803 2805 2807 2808 2905 2906 2907 2908 C'
    incorporeal_assets_advances: '237'
    incorporeal_assets_total: '109 201 203 205 206 207 208 237'
    incorporeal_assets_total_depreciations: '2801 2803 2805 2807 2808 2905 2906 2907 2908 C'
    corporeal_assets_land_parcels: '211'
    corporeal_assets_land_parcels_depreciations: '2811 2911 C'
    corporeal_assets_settlements: '212'
    corporeal_assets_settlements_depreciations: '2812 2912 C'
    corporeal_assets_enhancement: '217'
    corporeal_assets_enhancement_depreciations: '2817 2917 C'
    corporeal_assets_buildings: '213 214'
    corporeal_assets_buildings_depreciations: '2813 2814 2913 2914 C'
    corporeal_assets_equipments: '215'
    corporeal_assets_equipments_depreciations: '2815 2915 C'
    corporeal_assets_others: '218'
    corporeal_assets_others_depreciations: '2818 2918 C'
    corporeal_assets_in_progress: '231'
    corporeal_assets_in_progress_depreciations: '2931 C'
    corporeal_assets_advances: '2381'
    corporeal_assets_total: '21 231 2381'
    corporeal_assets_total_depreciations: '281 291 2931 C'
    alive_corporeal_assets_adult_animals: '241'
    alive_corporeal_assets_adult_animals_depreciations: '2841 2941 C'
    alive_corporeal_assets_young_animals: '242'
    alive_corporeal_assets_young_animals_depreciations: '2942 C'
    alive_corporeal_assets_service_animals: '243'
    alive_corporeal_assets_service_animals_depreciations: '2843 2943 C'
    alive_corporeal_assets_perennial_plants: '246'
    alive_corporeal_assets_perennial_plants_depreciations: '2846 2946 C'
    alive_corporeal_assets_others: '247'
    alive_corporeal_assets_others_depreciations: '2847 2947 C'
    alive_corporeal_assets_in_progress: '234'
    alive_corporeal_assets_in_progress_depreciations: '2934 C'
    alive_corporeal_assets_advances: '2384'
    alive_corporeal_assets_total: '24 234 2384'
    alive_corporeal_asset_total_depreciations: '284 294 2934 C'
    financial_assets_participations: '261 262 266'
    financial_assets_participations_depreciations: '2961 2962 2966 C'
    financial_assets_participations_debts: '267 268'
    financial_assets_participations_debts_depreciations: '2967 2968 C'
    financial_assets_others: '271 272 274 275 276'
    financial_assets_others_depreciations: '2971 2972 2974 2975 2976 C'
    financial_assets_total: '26 27'
    financial_asset_total_depreciations: '296 297 C'
    long_cycle_alive_products_animals: '31'
    long_cycle_alive_products_animals_depreciations: '391 C'
    long_cycle_alive_products_plant_advance: '331'
    long_cycle_alive_products_plant_advance_depreciations: '3931 C'
    long_cycle_alive_products_plant_in_ground: '332 338'
    long_cycle_alive_products_plant_in_ground_depreciations: '3932 3938 C'
    long_cycle_alive_products_wine: '351 352'
    long_cycle_alive_products_wine_depreciations: '3951 3952 C'
    long_cycle_alive_products_others: '356 357 358'
    long_cycle_alive_products_others_depreciations: '3956 3957 3958 C'
    long_cycle_alive_products_total: '31 33 35'
    long_cycle_alive_products_total_depreciations: '391 393 395 C'
    short_cycle_alive_products_animals: '32'
    short_cycle_alive_products_animals_depreciations: '392 C'
    short_cycle_alive_products_plant_advance: '341'
    short_cycle_alive_products_plant_advance_depreciations: '3941 C'
    short_cycle_alive_products_plant_in_ground: '348'
    short_cycle_alive_products_plant_in_ground_depreciations: '3948 C'
    short_cycle_alive_products_others: '36'
    short_cycle_alive_products_others_depreciations: '396 C'
    short_cycle_alive_products_total: '32 34 36'
    short_cycle_alive_products_total_depreciations: '392 394 396 C'
    stocks_supply: '30'
    stocks_supply_depreciations: '390 C'
    stocks_end_products: '374 375 376'
    stocks_end_products_depreciations: '3974 3975 3976 C'
    stocks_others_products: '371 372 373 377 378'
    stocks_others_products_depreciations: '3971 3972 3973 3977 3978 C'
    stocks_total: '30 37'
    stocks_total_depreciations: '390 397 C'
    entities_advance_giveables: '4091'
    entities_client_receivables: '411 4131 416 417 4181 4188'
    entities_client_receivables_depreciations: '4916'
    entities_others_clients: '412 4132 4182'
    entities_others_clients_depreciations: '4912'
    entities_state_receivables: '445 D'
    entities_associate_receivables: '4551 D, 4552 D'
    entities_associate_receivables_depreciations: '4955'
    entities_other_receivables: '4096 4097 4098 425 4287 4387, 441 !4419, 443 D, 444 D, 4487, 451 D, 452 D, 453 D, 454 D, 456 D, 458 D, 461 D, 462 465, 467 D, 4687, 478 D'
    entities_other_receivables_depreciations: '4951 4952 4953 4954 4958 496'
    entities_investment_security: '502 503 504 505 506 507 508'
    entities_investment_security_depreciations: '5903 5904 5906 5908'
    entities_reserve: '472 D, 511 , 512 D, 514 D , 515 516 , 517 D, 5187 53 54'
    entities_advance_charges: '486 481'
    entities_assets_gaps: '470 471 D, 476'
    entities_total: '4091 411 4131 416 417 4181 4188 412 4132 4182, 445 D, 4551 D, 4552 D, 4096 4097 4098 425 4287 4387, 441 !4419, 443 D, 444 D, 4487, 451 D, 452 D, 453 D, 454 D, 456 D, 458 D, 461 D, 462 465, 467 D, 4687, 478 D, 502 503 504 505 506 507 508 511, 512 D, 514 D , 515 516 , 517 D, 5187 53 54 486 481, 470 471 D, 476'
    entities_total_depreciations: '4916 4912 4955 4951 4952 4953 4954 4958 496 5903 5904 5906 5908'
    capitals_values: '1011 1012 108 C, 1013 1014 1015 1018 1015 C'
    capitals_emissions_and_reevaluation_gaps: '104 105 C'
    capitals_liability_reserves: '106 C'
    capitals_anew_reports: '11'
    capitals_profit_or_loss: '- 12'
    capitals_investment_subsidies: '13 C'
    capitals_derogatory_depreciations: '145 C'
    capitals_mandatory_provisions: '142 143 144 146 147 148 C'
    capitals_risk_and_charges_provisions: '151 153 155 156 157 158 C'
    debts_land_parcel_loans: '1641 C'
    debts_others_loans: '1642 1643 C'
    debts_associate_locked_debts: '4553 4554 C'
    debts_cashe_debts: '519, 512 C, 514 C, 517 C, 5186'
    debts_other_financial_debts: '161 163 165 1675 168 C, 17 426, 451 C, 456 C, 458 C'
    others_debts_advance_receivables: '4191'
    others_debts_supplier_receivables: '401 4031 4081 4088 402 4032 4082, 472 C'
    others_debts_state_debts: '445 C'
    others_debts_social_debts: '421 422 424 427 4282 4284 4286 431 437 4382 4386 442, 443 444 C, 446 447 4482 4486 457'
    others_debts_associate_debts: '4551 C, 4552 C'
    others_debts_fixed_asset_debts: '269 279 404 405 4084'
    others_debts_others: '4196 4197 4198 4419, 452 453 454 461 467 478 C, 464 4686 509'
    others_debts_advance_products: '487'
    others_debts_liabilities_gaps: '470 471 C, 477'
fr_pcg82:
  profit_and_loss_statement:
    products_sales: '707 7097 C'
    productions_sales: '701 702 703 7091 7092 C'
    services_sales: '704 705 706 708 7094 7095 7096 7098 C'
    inventory_variations: '7133 7134 7135 C'
    capitalised_production: '72 73 C'
    subsidies: '74 C'
    provisions_revenues: '781 791 C'
    other_products: '751 752 753 758 C'
    merchandises_purchases: '607 6087 6097 D'
    merchandises_purchases_stocks_variation: '6037 D'
    products_purchases: '601 602 6081 6091 6092 D'
    purchases_stocks_variation: '6031 6032 D'
    other_purchases: '604 605 606 61 62 6094 6095 6096 D'
    taxes: '631 633 635 637 D'
    wages: '641 644 D'
    social_expenses: '645 646 647 648 D'
    depreciations_inputations_expenses: '6811 6812 6816 6817 6815 D'
    other_expenses: '651 653 654 658 D'
    products_subtotal: '70 71 72 74 751 752 753 758 781 791 C'
    charges_subtotal: '60 61 62 63 64 651 653 654 658 6811 6812 6815 6816 6817 D'
    exploitation_result: '70 71 72 74 751 752 753 758 781 791 C, - 60 61 62 63 64 651 653 654 658 6811 6812 6815 6816 6817'
    financial_participations: '761 C'
    financial_debts: '761 762 C'
    financial_others_interests: '763 764 765 768 C'
    financial_depreciations: '786 796 C'
    financial_positive_change: '766 C'
    financial_net_cession_values: '767 C'
    financial_products_subtotal: '76 786 796 C'
    financial_asset_dotations: '686 D'
    financial_interests_and_charges: '661 664 665 668 D'
    financial_negative_change: '666 D'
    financial_net_cession_debts: '667 D'
    financial_expenses_subtotal: '66 686 D'
    financial_result: '76 786 796 C, - 66 686'
    before_taxe_result: '70 71 72 74 75 781 791 76 786 796 C, - 60 61 62 63 64 65 681 66 686'
    exceptional_products_on_management_operations: '771 C'
    exceptional_products_on_assets_cessions: '775 C'
    exceptional_products_on_capital_operations: '777 778 C'
    exceptional_products_on_provisions: '787 797 C'
    exceptional_products_subtotal: '77 787 797 C'
    exceptional_expenses_on_management_operations: '671 673 D'
    exceptional_expenses_on_assets_cessions: '675 D'
    exceptional_expenses_on_capital_operations: '678 D'
    exceptional_expenses_on_provisions: '687 D'
    exceptional_expenses_subtotal: '67 687 D'
    exceptional_result: '77 787 797 C, - 67 687'
    employee_involvement: '691 D'
    profit_taxe: '695 697 699 D'
    products_total: '7 C'
    charges_total: '6 D'
    exercice_result: '70 71 72 74 75 781 791 76 786 796 77 787 797 C, - 60 61 62 63 64 65 681 66 686 67 687 691 695 697 699'
  ratio:
    exercice_production: '70 71 72 73 751 752 753 758 C, !707 !7097'
    commercial_margin: '707 7097 C, - 607 6097 6087'
    production_purchases: '601 602 6081 6091 6092 6031 6032 D'
    production_others_charges: '605 606 61 62 6355 6095 6096 6098 D'
    added_value: '70 71 72 73 751 752 753 758 C, - 607 6097 6087 601 602 6081 6091 6092 6031 6032 605 606 61 62 6355 6095 6096 6098'
    taxes_and_wages: '63 64 D, !6355'
    subsidies: '742 743 744 745 C'
    operating_margin: '70 71 72 73 751 752 753 758 742 743 744 745 C, - 607 6097 6087 601 602 6081 6091 6092 6031 6032 605 606 61 62 6095 6096 6098 63 64'
  balance_sheet:
    unsubcribed_capital: '109'
    incorporeal_assets_creation_costs: '201'
    incorporeal_assets_creation_costs_depreciations: '2801 C'
    incorporeal_assets_others: '203 205 206 207 208'
    incorporeal_assets_others_depreciations: '2803 2805 2807 2808 2905 2906 2907 2908 C'
    incorporeal_assets_advances: '237'
    incorporeal_assets_total: '109 201 203 205 206 207 208 237'
    incorporeal_assets_total_depreciations: '2801 2803 2805 2807 2808 2905 2906 2907 2908 C'
    corporeal_assets_land_parcels: '211'
    corporeal_assets_land_parcels_depreciations: '2811 2911 C'
    corporeal_assets_settlements: '212'
    corporeal_assets_settlements_depreciations: '2812 2912 C'
    corporeal_assets_enhancement: '217'
    corporeal_assets_enhancement_depreciations: '2817 2917 C'
    corporeal_assets_buildings: '213 214'
    corporeal_assets_buildings_depreciations: '2813 2814 2913 2914 C'
    corporeal_assets_equipments: '215'
    corporeal_assets_equipments_depreciations: '2815 2915 C'
    corporeal_assets_others: '218'
    corporeal_assets_others_depreciations: '2818 2918 C'
    corporeal_assets_in_progress: '231'
    corporeal_assets_in_progress_depreciations: '2931 C'
    corporeal_assets_advances: '2381'
    corporeal_assets_total: '21 231 2381'
    corporeal_assets_total_depreciations: '281 291 2931 C'
    financial_assets_participations: '261 262 266'
    financial_assets_participations_depreciations: '2961 2962 2966 C'
    financial_assets_participations_debts: '267 268'
    financial_assets_participations_debts_depreciations: '2967 2968 C'
    financial_assets_others: '271 272 274 275 276'
    financial_assets_others_depreciations: '2971 2972 2974 2975 2976 C'
    financial_assets_total: '26 27'
    financial_asset_total_depreciations: '296 297 C'
    stocks_supply: '30'
    stocks_supply_depreciations: '390 C'
    stocks_end_products: '374 375 376'
    stocks_end_products_depreciations: '3974 3975 3976 C'
    stocks_others_products: '371 372 373 377 378'
    stocks_others_products_depreciations: '3971 3972 3973 3977 3978 C'
    stocks_total: '30 37'
    stocks_total_depreciations: '390 397 C'
    entities_advance_giveables: '4091'
    entities_client_receivables: '411 4131 416 417 4181 4188'
    entities_client_receivables_depreciations: '4916'
    entities_others_clients: '412 4132 4182'
    entities_others_clients_depreciations: '4912'
    entities_state_receivables: '445 D'
    entities_associate_receivables: '4551 D, 4552 D'
    entities_associate_receivables_depreciations: '4955'
    entities_other_receivables: '4096 4097 4098 425 4287 4387, 441 !4419, 443 D, 444 D, 4487, 451 D, 452 D, 453 D, 454 D, 456 D, 458 D, 461 D, 462 465, 467 D, 4687, 478 D'
    entities_other_receivables_depreciations: '4951 4952 4953 4954 4958 496'
    entities_investment_security: '502 503 504 505 506 507 508'
    entities_investment_security_depreciations: '5903 5904 5906 5908'
    entities_reserve: '511 , 512 D, 514 D , 515 516 , 517 D, 5187 53 54'
    entities_advance_charges: '486 481'
    entities_assets_gaps: '470 471 D, 476'
    capitals_values: '1011 1012 108 C, 1013 1014 1015 1018 1015 C'
    capitals_emissions_and_reevaluation_gaps: '104 105 C'
    capitals_liability_reserves: '106 C'
    capitals_anew_reports: '11 C'
    capitals_profit_or_loss: '12 C'
    capitals_investment_subsidies: '13 C'
    capitals_derogatory_depreciations: '145 C'
    capitals_mandatory_provisions: '142 143 144 146 147 148 C'
    capitals_risk_and_charges_provisions: '151 153 155 156 157 158 C'
    debts_land_parcel_loans: '1641 C'
    debts_others_loans: '1642 1643 C'
    debts_associate_locked_debts: '4553 4554 C'
    debts_cashe_debts: '519, 512 C, 514 C, 517 C, 5186'
    debts_other_financial_debts: '161 163 165 1675 168 C, 17 426, 451 C, 456 C, 458 C'
    others_debts_advance_receivables: '4191'
    others_debts_supplier_receivables: '401 4031 4081 4088 402 4032 4082 C'
    others_debts_state_debts: '445 C'
    others_debts_social_debts: '421 422 424 427 4282 4284 4286 431 437 4382 4386 442, 443 444 C, 446 447 4482 4486 457'
    others_debts_associate_debts: '4551 C, 4552 C'
    others_debts_fixed_asset_debts: '269 279 404 405 4084'
    others_debts_others: '4196 4197 4198 4419, 452 453 454 461 467 478 C, 464 4686 509'
    others_debts_advance_products: '487'
    others_debts_liabilities_gaps: '470 471 C, 477'
