#!/usr/bin/env ruby
require 'active_support/core_ext'
require 'optparse'
require 'pathname'
require 'fileutils'

STDOUT.sync = true

@simulate = false

def execute(command)
  puts command
  unless @simulate
    system(command)
  end
end

table = ARGV.shift

unless $PROGRAM_NAME.match(/^(.\/)?script\//)
  puts "Script must be started from Rails root."
  exit 0
end

raise "Not table given" if table.blank?

root = Pathname.new(".")

records = table
record = records.singularize
puts "Removes #{record}"
execute("git rm app/models/#{record}.rb")
execute("git rm app/controllers/backend/#{records}_controller.rb")
execute("git rm app/helpers/backend/#{records}_helper.rb")
execute("git rm -fr app/views/backend/#{records}")
execute("git rm test/fixtures/#{records}.rb")
execute("git rm test/unit/backend/#{record}_test.rb")
execute("git rm test/functional/backend/#{records}_controller_test.rb")
