#!/bin/bash
app=$1
version=$2
log=$3
resdir=$4

release=${app}-${version}

rm -fr packages
mkdir -p packages

# dh_make -i -c gpl3 -n -e brice.texier@ekylibre.org -p ${app}_${version}

debdir="`pwd`/debian"

root="`pwd`/files"
rm -fr $root
mkdir -p $root

ln -s $debdir $root/debian

control=$debdir/control

rm -fr copy
cp -rL ${app} copy
find copy -name .svn* -print0 | xargs -0 rm -rf
find copy -name .git* -print0 | xargs -0 rm -rf
find copy -name "*~"  -print0 | xargs -0 rm -rf
find copy -name "#*#" -print0 | xargs -0 rm -rf

pushd copy
echo "Rails.application.config.action_controller.relative_url_root = '/ekylibre'" > config/initializers/relative_url_root.rb
bundle install --quiet
echo "production:" > config/database.yml
echo "  adapter: sqlite3" >> config/database.yml
echo "  database: db/production.sqlite3" >> config/database.yml
bundle exec rake assets:precompile RAILS_ENV=production
popd

# Deactivates other adapters
sed -i -e 's/gem "mysql/# gem "mysql/g' -i -e 's/gem "sqlite/# gem "sqlite/g' -i -e "s/gem 'mysql/# gem 'mysql/g" -i -e "s/gem 'sqlite/# gem 'sqlite/g" copy/Gemfile
rm -f copy/config/database.yml

cd $root
# dpkg --build $root
dpkg-buildpackage -us -uc -b >> $log

cd ..

rm -fr copy
rm -fr $root

mv ${app}_*.deb packages/