#!/bin/sh
app=$1
version=$2
log=$3
resdir=$4

release=${app}-${version}

rm -fr packages
mkdir -p packages

# root="`pwd`/${release}"


# debdir="${root}/DEBIAN"

# rm -fr $root

# mkdir -p $debdir

# cd $root
# dh_make -i --createorig

# # control=$debdir/control
# # echo "Package: ${app}" > $control
# # echo "Version: ${version}" >> $control 
# # echo "Architecture: all" >> $control 
# # echo "Priority: optional" >> $control
# # echo "Homepage: http://www.ekylibre.org" >> $control
# # echo "Maintainer: Brice Texier <brice.texier@ekylibre.org>" >> $control 
# # echo "Description: Simple ERP for little business" >> $control
# # echo "Section: web" >> $control
# # echo "Depends: ruby (>=1.8.7), rubygems (>=1.3.7), ruby-dev (>=1.8.7), apache2 (>=2.2.4), libapache2-mod-passenger" >> $control
# # echo "Recommends: postgresql (>=8.3)" >> $control

# mkdir -p "$root/usr/share"
# cp -r ${app} "$root/usr/share/"

# dpkg --build $root
# dpkg-buildpackage -b
