#!/usr/bin/env ruby
require 'fileutils'
include FileUtils

here = File.expand_path('..', __FILE__)

# Copy database.yml like in real case
system("cp -f #{here}/database.#{ENV['DB']}.yml #{here}/../config/database.yml")

# Create Database manually
if ENV['DB'] == 'postgresql'
  system('psql -c "create database ekylibre_test;" -U postgres > /dev/null 2>&1')
elsif ENV['DB'] == 'mysql'
  system('mysql -e "create database ekylibre_test;" > /dev/null 2>&1')
end

