#!/usr/bin/env ruby
require 'fileutils'

icons = %w(new edit destroy search validate cancel lock unlock action up down left right configure column table duplicate point mark unmark true false page spreadsheet print filter mail nomail sort check divide load logout increment decrement close help merge spread rgreen rblue rblack nav)
states = %w(normal disabled active whited hover)

default_state = "normal"
default_size = 16
horizontal_space = 8
vertical_space = 8
x = default_size + horizontal_space
y = default_size + vertical_space
STDOUT.sync = true
for size in [default_size]
  icons_path = File.join(File.dirname(__FILE__), "icons")
  icons_path << "-#{size}" if size != default_size
  FileUtils.mkdir_p(icons_path)
  puts "Exporting in #{icons_path}:"
  icons.each_with_index do |icon, b|
    print " - #{icon}"
    states.each_with_index do |state, s|
      filename  = icon
      filename += "_#{state}" if state != default_state
      filename += ".png"
      file = File.join(icons_path, filename)
      unless File.exist?(file)
        cmd = "inkscape --without-gui"
        cmd << " --export-png=#{file}"
        cmd << " --export-area=#{b*x}:#{s*y}:#{b*x+default_size}:#{s*y+default_size}"
        cmd << " --export-background-opacity=0"
        cmd << " --export-width=#{size}"
        cmd << " --export-height=#{size}" 
        cmd << " icons.svg"
        `#{cmd}`
      end
      print "."
    end
    puts ""
  end
end
