#!/bin/bash
app=$1
version=$2
log=$3
resdir=$4

release=${app}-${version}

rm -fr packages
mkdir -p packages

if [ -n "`which makensis`" ]; then
    nsis_share=/usr/share/nsis
    if [ -e ${nsis_share}/Plugins/pwgen.dll ]; then
	echo " * Plugins and includes seems to be installed in ${nsis_share}." >> $log	
    else
	echo " * Install plugins and includes in ${nsis_share}." >> $log	
	sudo cp *.nsh ${nsis_share}/Include
	sudo cp *.dll ${nsis_share}/Plugins
    fi
    
    pushd ${app}
    mv public public-link
    mkdir public
    cp -r public-link/* public/
    rm public-link
    bundle install --quiet
    rake assets:precompile RAILS_ENV=production
    popd
    
    files="files"
    rm -fr ${files}
    mkdir -p ${files}/apps
    ln -s `pwd`/${app} ${files}/apps/${app}
    ln -s ${resdir}/* ${files}/
    makensis -DRELEASE=${release} -DVERSION=${version} -DRESOURCES=${files} -DIMAGES=images installer.nsi >> $log
    rm -fr ${files}
else
    echo " * No makensis command. Run 'sudo apt-get install nsis'"
    echo " * No makensis command. Run 'sudo apt-get install nsis'" >> $log
fi

