#!/bin/bash

set -e

CLI="ekylibre"

rake_commands="db:migrate"

DB="ekylibre_production"
USER="ekylibre"

# set postgis on db
su postgres -c "psql -c 'CREATE DATABASE ${DB} WITH OWNER ${USER};'"
su postgres -c "psql -d ${DB} -c 'CREATE SCHEMA IF NOT EXISTS postgis AUTHORIZATION ${USER};'"
su postgres -c "psql -d ${DB} -c 'CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA postgis;'"

# set SECRET_TOKEN env variable
secret_token=$(${CLI} config:get SECRET_KEY_BASE || ${CLI} run rake -s secret | tail -1)
${CLI} config:set SECRET_KEY_BASE="$secret_token"

# migrate
${CLI} run rake ${rake_commands} || true

# install default instance
${CLI} run rake first_run name=main folder=default || true

# scale
${CLI} scale web=1 || true

# set
${CLI} config:set ELEVATOR=header

# restart
service ${APP_NAME} restart

# setup nginx configuration
cat > /etc/nginx/sites-available/default <<EOF
server {
  listen          80;
  location / {
    proxy_pass       http://localhost:6000;
    proxy_set_header X-Tenant main;
  }
}
EOF

# restart nginx
sudo service nginx restart
