#!/usr/bin/env bash

# Set Ruby version
echo "ruby '2.2.1'" >> Gemfile

# Set complementary gems
echo "gem 'rails_12factor'" >> Gemfile

# Updates Gemfile.lock
bundle update

# Set DB config
# cp -f packaging/conf/database.yml config/database.yml

# Removes useless files
rm -fr log/*.log tmp/* test doc private/* db/first_runs .sass-cache coverage *~
