# The order of require define the default order of call in execution
require 'ekylibre/first_run/loaders/base'
require 'ekylibre/first_run/loaders/general_ledger'
require 'ekylibre/first_run/loaders/entities'
require 'ekylibre/first_run/loaders/land_parcels'
require 'ekylibre/first_run/loaders/buildings'
require 'ekylibre/first_run/loaders/equipments'
require 'ekylibre/first_run/loaders/products'
require 'ekylibre/first_run/loaders/animals'
require 'ekylibre/first_run/loaders/productions'
require 'ekylibre/first_run/loaders/analyses'
require 'ekylibre/first_run/loaders/sales'
require 'ekylibre/first_run/loaders/deliveries'
require 'ekylibre/first_run/loaders/purchases'
require 'ekylibre/first_run/loaders/bank_statements'
require 'ekylibre/first_run/loaders/interventions'
require 'ekylibre/first_run/loaders/demo'
