require_relative 'erp/cultivable_zones'
require_relative 'erp/entities'
require_relative 'erp/georeadings'
require_relative 'erp/land_parcels'
require_relative 'erp/plants'
require_relative 'erp/settings'
